volumes:
   django_local_data: {}
   django_local_postgres_data: {}

services:
#  postgres_db:
#    image: postgres:11
#    container_name: local_postgres_container
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=db_name
#    volumes:
#      - django_local_postgres_data:/var/lib/postgresql/data
  django_web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django_image
    container_name: django_web_container
    command: sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
#    command: bash -c "python manage.py migrate && python manage.py runserver"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:S@patidar*86@localhost:5432/db_name
#    depends_on:
#      - postgres_db
    volumes:
      - django_local_data:/data
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=suraj@codebreakerhub.com
#      - PGADMIN_DEFAULT_PASSWORD=test@12345
#    ports:
#      - "5050:80"
#    depends_on:
#      - postgres_db